[package]
name = "tame-sentry"
version = "0.1.0"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"

[dependencies]
breakpad-handler = { version = "0.1.0", path = "./breakpad-handler" }

[workspace]
members = [
    "breakpad-handler",
    "breakpad-sys",
]